#playbook for creating infra for ec2 instance in this will create vpc ,subnet,igw, route table and ec2 instance by calling role aws-infra.

- name: Create AWS Instance
  hosts: localhost
  gather_facts: false
  vars:
    instance_name: Ansible_instance2
  roles:
  - aws-infra


- name: Install Postgresql
  hosts: NewServer
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
  roles:
    #- Add a postgres sql roles here 

