---

- name: yum install postgresql96
  yum : 
   name: postgresql-server
   state: present
  become: yes
  become_user: root
   
- name: yum install postgresql old version 
  command : sudo yum install postgresql-contrib -y

- name: setup db
  command : sudo postgresql-setup initdb

- name: start postgres
  command : sudo systemctl start postgresql

- name : enable postgres
  command : sudo systemctl enable postgresql

- name : install python-psycopg2
  command : sudo yum install python-psycopg2
