---

- name: yum install postgresql96
  yum : 
   name: postgresql-server
   state: installed
  become: yes
  become_user: root
   
- name: yum install postgresql old version 
  yum : 
   name: postgresql-contrib
   state: installed
  become: yes
  become_user: root
 
- name: Setup Db
  become: yes
  become_user: postgres
  command: postgresql-setup initdb

- name: Start PostgreService
  systemd:
    state: started
    name: postgresql

- name : enable postgresql
  systemd:
    name: postgresql
    enabled: yes
    
- name: install python-psycopg2
  yum : 
   name: python-psycopg2
   state: installed
  become: yes
  become_user: root
