---

- name: yum install download packgaes
  become: yes
  become_user: ec2-user
  command: yum install https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm
  
  
- name: yum install postgresql96
  yum : 
   name: postgresql-server
   state: present
  become: yes
  become_user: root
   
- name: yum install postgresql old version 
  yum : 
   name: postgresql-contrib
   state: present
  become: yes
  become_user: root
 
- name: Setup Db
  become: yes
  become_user: root
  command: postgresql-setup initdb

- name: Start PostgreService
  systemd:
    state: started
    name: postgresql

- name : enable postgresql
  systemd:
    name: postgresql
    enabled: yes
    
- name: install python-psycopg2
  yum : 
   name: python-psycopg2
   state: present
  become: yes
  become_user: root
